### PR TITLE
Event service

### PR DESCRIPTION
**Pull request by nsmkhn**
The purpose of this PR is to discuss & understand & implement websockets in webserver.

Changes made in scope of this PR so far:
- added websocket route to the webserver which clients can connect to and subscribe to particular event types(topics)
- added task to webserver which constantly listens for new events(files) in FS and spreads them across connected clients via websockets

@StuartFarmer @JeffWScott I would appreciate your comments regarding how this should be implemented because I don't have a clear picture of what we need at the moment

### CODE REVIEW

**Comment by JeffWScott** [comment]
It looks like you are importing events.py.  Instead you need to connect to an events.py instance (via websocket).  Then you need to pipe that information to the clients connected to your new webserver.py endpoint.

Events is a microservice that will run and pickup files (events) from the filesystem created by the node.  There could be multiple instances of webserver.py running and connecting to it.

the last time I spoke to @StuartFarmer he was unsure of the status of events.py and if it could be run as a microservice AS IS.

What I think actually needs to happen is that @StuartFarmer needs to take a quick look at events and see what work is needed there.

**Comment by JeffWScott** [comment]
@nsmkhn I talked it over with @StuartFarmer 

Looks like there is work on the event server that needs to be completed.

event.py attempted to mix the file reading and writing of file events with websockets and "topics".  There is already a websocket implementation called [socket.io](www.socket.io) that does this.

To make it a standalone microservice let's replace all the websocket code with a [socket.io AyncServer](https://python-socketio.readthedocs.io/en/latest/intro.html).

Scope of Work:
Keep Event, EventWriter and Event Listener
Replace Connection, Connection Manager and WebsocketServer with socket.io implementation.
Write Test Cases

Details:
1) Socket.io works by allowing clients websockets to "join" rooms (topics).  Then the server can send information to those rooms and all the clients in that room will get sent the information. Clients can join multiple rooms.
2) The Events from events.py are not structured yet.  But ideally we would structure them as JSON with the following properties:
``` json
{
  topics: ["new_block"],
  data: {number: 101, hash:"bb67232f70994134ed79"}
}
```
The socket.io server should call "get_events" on a timer, and when it finds new events it will process them one at a time, emitting the "data" package to each topic.

Example:
``` python
# events.py

events = event_listener.get_events()
for event in events:
    for topic in event.topics:
        sio.emit(topic, event.data)
```
[emitting events in socket.io](https://python-socketio.readthedocs.io/en/latest/server.html#emitting-events)

webserver.py should use the socket.io client to connect to the event.py socket.io server.  
Example:
``` python
# webserver.py

## Connect to event service on webserver startup (port should be an arg)
sio.connect('http://localhost:<port>')

@sio.on('new_block')
def ws_new_block(data):
    # send data to all connected websockets
```
[socket.io event handlers](https://python-socketio.readthedocs.io/en/latest/client.html#defining-event-handlers)

**Comment by nsmkhn** [comment]
@JeffWScott I've updated the PR with things I've done so far. I would appreciate your feedback. I wonder if I'm moving in right direction.
At the moment events received by webserver from event service are not broadcasted across client websockets yet. I need to figure out how to make it work.

**Comment by nsmkhn** [comment]
@JeffWScott I've pushed event service test cases, please take a look.

**Pull request merged**
